[2017-12-18 22:01:43,585] I Max date config 2017-07-06 00:00:00, nginx log filename: nginx-access-ui.log-20170706.gz
[2017-12-18 22:01:54,131] I Max date config 2017-07-06 00:00:00, nginx log filename: nginx-access-ui.log-20170706.gz
[2017-12-18 22:02:55,422] I Len of list parsed urls: 2564763
[2017-12-18 22:02:57,677] I dicts len: 237088
[2017-12-18 22:02:57,730] I all count urls: 2564763
[2017-12-18 22:02:57,962] I all_time_req: 1007769.054
[2017-12-18 22:03:00,501] I statistic time: 1.1061597983
[2017-12-18 22:03:02,336] I mtime of ts-file: 1513623782.33
[2017-12-18 22:04:37,743] I Max date config 2017-07-06 00:00:00, nginx log filename: nginx-access-ui.log-20170706.gz
[20:05:14 27-Dec-2017] I Max date config 2017-07-06 00:00:00, nginx log filename: nginx-access-ui.log-20170706.gz
[19:32:26 01-Jan-2018] I Max date config 2017-07-06 00:00:00, nginx log filename: nginx-access-ui.log-20170706.gz
[19:33:25 01-Jan-2018] I Len of list parsed urls: 2613686
[19:33:27 01-Jan-2018] I dicts len: 256565
[19:33:28 01-Jan-2018] I all count urls: 2613686
[19:33:28 01-Jan-2018] I all_time_req: 1007769.054
[19:33:31 01-Jan-2018] I statistic time: 1.07601356506
[19:33:33 01-Jan-2018] I mtime of ts-file: 1514824413.86
[19:37:00 01-Jan-2018] I Max date config 2017-07-06 00:00:00, nginx log filename: nginx-access-ui.log-20170706.gz
[19:37:00 01-Jan-2018] I Report for log (datetime.datetime(2017, 7, 6, 0, 0), 'nginx-access-ui.log-20170706.gz') already exist
[19:37:20 01-Jan-2018] I Max date config 2017-07-06 00:00:00, nginx log filename: nginx-access-ui.log-20170706.gz
[19:38:21 01-Jan-2018] E Less 66% success parsed lines
None
[19:38:21 01-Jan-2018] E Less 66% success parsed lines
Traceback (most recent call last):
  File "log_analyzer.py", line 185, in <module>
    main(dict_of_config)
  File "log_analyzer.py", line 139, in main
    my_list = open_logs(filename=os.path.join(dict_of_config['LOG_DIR'], filename), parse_level=dict_of_config['REPORT_DIR'])
  File "log_analyzer.py", line 95, in open_logs
    parsed_list = parse_logs(log_file, parse_level)
  File "log_analyzer.py", line 83, in parse_logs
    raise Exception('Less 66% success parsed lines')
Exception: Less 66% success parsed lines
